// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCF7iW7kJrBdOgOtVIN6j1UXIZEdhc5hY',
    appId: '1:973064254676:android:edf082f8021ed62d513741',
    messagingSenderId: '973064254676',
    projectId: 'kubenmat-bf328',
    storageBucket: 'kubenmat-bf328.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMWxExALoHqS0_MIUePbe_OqZM4PXMG7s',
    appId: '1:973064254676:ios:2231c54f67c8555c513741',
    messagingSenderId: '973064254676',
    projectId: 'kubenmat-bf328',
    storageBucket: 'kubenmat-bf328.appspot.com',
    androidClientId: '973064254676-592q8gmtld0m0orn7t2nc3bknsb4h1fc.apps.googleusercontent.com',
    iosClientId: '973064254676-m2ktb9hgim7av9mv6or2kpc771tphp7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.kubenmat',
  );
}
